# Generated by Django 6.0.3 on 2026-05-20 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('cns', models.CharField(max_length=15, unique=True)),
                ('data_nascimento', models.DateField()),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('microarea', models.CharField(max_length=10)),
                ('dum', models.DateField(blank=True, null=True, verbose_name='Data da Última Menstruação (DUM)')),
                ('dpp', models.DateField(blank=True, null=True, verbose_name='Data Provável do Parto (DPP)')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField()),
                ('tipo', models.CharField(choices=[('Medica', 'Consulta Médica'), ('PreNatal', 'Consulta Pré-Natal'), ('Puericultura', 'Puericultura'), ('Odonto', 'Odontológica'), ('Enfermagem', 'Enfermagem')], max_length=50)),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='app.cidadao')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Pressao', 'Aferição de Pressão Arterial'), ('PesoAltura', 'Medição de Peso e Altura'), ('Hemoglobina', 'Hemoglobina Glicada'), ('Pes', 'Avaliação dos Pés (Diabético)'), ('Citopatologico', 'Citopatológico (Preventivo)'), ('Mamografia', 'Mamografia'), ('TesteRapido', 'Teste Rápido (Sífilis/HIV)')], max_length=50)),
                ('data_exame', models.DateField()),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='app.cidadao')),
            ],
        ),
        migrations.AddField(
            model_name='cidadao',
            name='grupos_de_risco',
            field=models.ManyToManyField(blank=True, to='app.gruporisco'),
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Influenza', 'Influenza'), ('dTpa', 'dTpa (Gestante)'), ('Pentavalente', 'Pentavalente'), ('Polio', 'Poliomielite'), ('Pneumo', 'Pneumocócica'), ('HPV', 'HPV')], max_length=50)),
                ('data_aplicacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Realizada', max_length=50)),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='app.cidadao')),
            ],
        ),
        migrations.CreateModel(
            name='VisitaACS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita', models.DateField()),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='app.cidadao')),
            ],
        ),
    ]
